### ISSUE TITLE
Create HTML style for provided cover page / documents

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/gbdoc-style#1]
@pierrefortier , in this repo there is an image scan of the cover page, the content in DOCX and PDF, and also the HTML representation of it.

Our goal is to make the HTML representation look nice but somehow adhering to the style of the original styles (scan, DOCX -- the PDF is only for your reference if the DOCX doesn't work for you).

Can you help provide a design + template for this HTML? Functionality wise the CSD features are perfect.

We'll be using this with our tool: https://github.com/riboseinc/asciidoctor-gb/

Thanks!

**Comment by ronaldtse** [comment]
cc: @opoudjis

**Comment by ronaldtse** [comment]
You can see more instances of this style here: https://github.com/riboseinc/gbdoc/tree/master/reference-docs

**Comment by pierrefortier** [comment]
Sounds good, I'll have a look at it today. Thanks!

**Comment by pierrefortier** [comment]
Updated! Let me know if there are any bugs / changes. :)

**Comment by ronaldtse** [comment]
@opoudjis looks like this is ready to be merged into asciidoctor-gb?

**Comment by ronaldtse** [comment]
Actually, @pierrefortier could you help update the style to reflect this cover page shown here (https://github.com/riboseinc/gbdoc-style/issues/9)? Thanks!

(this is the compliance-optimized page)

**Comment by opoudjis** [comment]
Done
