### ISSUE TITLE
T&D clause numbers not treated as normal clauses

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/gbdoc-style#11]
A picture is worth a thousand words, from the same document. The T&D clauses ought to be tagged identically to normal sections?

Right:

<img width="723" alt="screen shot 2018-04-07 at 2 14 44 am" src="https://user-images.githubusercontent.com/11865/38437265-7ef84692-3a09-11e8-9da3-b849f23a8dab.png">

Wrong:

<img width="324" alt="screen shot 2018-04-07 at 2 13 10 am" src="https://user-images.githubusercontent.com/11865/38437276-835d2ba8-3a09-11e8-8a6e-18cff50b545a.png">

**Comment by opoudjis** [comment]
Both ISO (Rice document) and GB/T 1.1 explicitly say the term number should appear on a separate line from the primary term. Where is this requirement coming from?

**Comment by ronaldtse** [comment]
The idea is to consolidate styling of all clause numbers and clause titles (and allow them to have the link anchor).

For example when there are subsections inside the T&D section, we don’t want to have some clause numbers to have an anchor but some not.

**Comment by opoudjis** [comment]
So this is about anchors, not the numbers being on the same line (so the first example isn't right either)

**Comment by ronaldtse** [comment]
Oh the first example is just a normal clause (it’s a section 6). My point was to show that the T&D ones don’t have anchors. 

The most important thing for me is to have the tagging semantically correct. Styling and layout should really be the job of CSS. 

In a more improved HTML document, perhaps we can even show the definition of defined terms used in the content on hover.

**Comment by opoudjis** [comment]
I'm looking at the HTML output of GB, and they *are* tagged the same:

````
<h1 id="988b529b-5402-4702-b613-1f183294b7da">2.&#x3000;Normative References</h1>
...
<h1 id="0975fe43-345b-4e43-9aa9-8219cc916c29">3.&#x3000;Terms and Definitions</h1>
....
<h2 class="TermNum" id="husked_rice">3.2</h2><p class="Terms">&#x3000;husked rice</p>
....
<h2 class="TermNum" id="_milled_rice">3.3</h2><p class="Terms">&#x3000;milled rice</p>
````

I can't tell you why the anchors are showing up in one and not the other in the version you have screen-grabbed, but I'm not seeing anything about the header markup that needs to change.
