### ISSUE TITLE
Provide GB document instead of GM for additional styling

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/gbdoc-style#4]
Also provide it with a draft stage text/style -- and we should style that as well

(from https://github.com/riboseinc/gbdoc-style/pull/3)

**Comment by opoudjis** [comment]
I'm assuming this means that I should generate a document in GB in draft mode, for you to apply styling to. Attached.

[gb-gmt-0009-2012-gbdoc.zip](https://github.com/riboseinc/gbdoc-style/files/1862658/gb-gmt-0009-2012-gbdoc.zip)

**Comment by opoudjis** [comment]
ignore that; providing new document reflecting https://github.com/riboseinc/asciidoctor-gb/issues/52

**Comment by opoudjis** [comment]
[rice.gb.zip](https://github.com/riboseinc/gbdoc-style/files/1862823/rice.gb.zip)

**Comment by ronaldtse** [comment]
@pierrefortier could you help update styling using this new file? Thanks!
