### ISSUE TITLE
Improving cover page styling

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/gbdoc-style#5]
The current cover page styling is identical to the Word doc, but we should improve on it.

@pierrefortier could you help improve the styling and layout of it -- so that it looks professional and clear?

Thanks!

**Comment by pierrefortier** [comment]
Sure thing, I'll have a look at it tomorrow.

**Comment by opoudjis** [comment]
Is this ticket separate from #9?

**Comment by ronaldtse** [comment]
This ticket is now for the “human-optimized” cover page :wink:

**Comment by ronaldtse** [comment]
@pierrefortier any updates on this? Thanks!

**Comment by opoudjis** [comment]
Closing
