### ISSUE TITLE
GB Word-like HTML coverpage

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/gbdoc-style#9]
This task is... horrid.

The GB/T 1.1 spec has some quite mechanical formatting requirements for its coverpage:

https://github.com/riboseinc/asciidoctor-gb/issues/58 
https://github.com/riboseinc/asciidoctor-gb/issues/56
https://github.com/riboseinc/asciidoctor-gb/issues/57

Standards compliance to GB means that you replicate the measurements and fonts of the coverpage. Counterintuitive and retrograde though it be, we will need to generate HTML whose coverpage information looks like the Word document. (Yes, that means treating the HTML output like an A4 page.)

There is prior art to this, but none of the Word documents floating around seem to actually adhere to the GB/T 1.1 spec. (In fact, as of Word 2016, they'd have found it very hard to, with Word disallowing Space Before after a page break.)

The prior art you should pay attention to is what I'm generating in Word. However, Word HTML is so ugly, you may well prefer to start from scratch with your CSS. God knows I would.

https://github.com/riboseinc/asciidoctor-gb/blob/master/lib/asciidoctor/gb/html/wordstyle.scss
https://github.com/riboseinc/asciidoctor-gb/blob/master/lib/asciidoctor/gb/html/word_gb_titlepage.html

To make the cm positioning happen, I am using Word Frames; you will see the cm measurements scattered through the HMTL and CSS. (You'll also see I've had to do a lot of trickery to get h1 to have space before, and that the space calculation is off—the line spacing eats into the frame height.) So there may be value in you extracting measurements out of the HTML and CSS; but honestly, it likely will be easier to start from scratch.

I am generating Word documents that comply with the measurements, and have uploaded them to https://github.com/riboseinc/gbdoc-rice . (Note that as of this writing, I have not done https://github.com/riboseinc/asciidoctor-gb/issues/57 yet.)

**Comment by ronaldtse** [comment]
@pierrefortier the latest iteration looks good indeed. However, sadly as mentioned by @opoudjis , we have been told to strictly adhere to the existing cover pages, which this is an example (for GB/T 19108, one of the latest publications). For exact measurements, please see the links provided by @opoudjis .

<img width="780" alt="screen shot 2018-04-06 at 1 30 30 am" src="https://user-images.githubusercontent.com/11865/38401527-d0a893ce-3988-11e8-9ba3-9a9fa3b2a646.png">

It may be best to implement page sizes in CSS for A4 (GB/T 1.1 specifies that A4 paper must be used):
* https://stackoverflow.com/questions/3341485/how-to-make-a-html-page-in-a4-paper-size-pages

P.S. I've also updated https://github.com/riboseinc/asciidoctor-gb/issues/58 to make the diagrams more clear.

**Comment by opoudjis** [comment]
Btw, I would not throw away your existing CSS. It makes more sense to treat this as a separate stylesheet overriding what you have currently done, so we can offer both human compatible and standards compatible cover pages.

**Comment by ronaldtse** [comment]
Agree, let’s have separate human optimized vs compliance optimized versions.

**Comment by pierrefortier** [comment]
Hi,

I've started looking over this task. As you suggested I've started working on a separate stylesheet for the compliance optimized version of the cover page. Right now the human optimized stylesheet has simply been commented out. My thinking at this point is to make a media query for print and add in all the page info there. This should allow the page to display in browser "normally", and in the correct print format when sent to a printer (or saved as a pdf). I'll have to run some tests on that. 

I have a few questions regarding the content, though.

1. The document I have contains english titles/subtitles, though the cover page standards/measurements don't seem to include any that I've seen. I've set them to "display: none;" for now, but I could simply style them similarly to the Chinese titles. 

2. Similar to 1, I haven't seen a guideline/measurements for the document stage. Should these be left out entirely?

3. Does the rest of the document need to be styled accordingly, or just the cover page? 

That's it for now I think. Thanks!

**Comment by opoudjis** [comment]
1. I have treated the subtitle in the measurements ticket as the English title, 1cm beneath the Chinese title; Chinese titles and subtitles consistently appear in the same line in all standards I've seen, so the measurements document does not correspond to actual practice. As stated in https://github.com/riboseinc/asciidoctor-gb/issues/56, English standard titles are in 14pt. (And note that Chinese standard titles in real life have been 26pt, not 72pt.)

2. The document stage is not accounted for in the spec, but it meant to be there, and is provided for in the old official Word template. It appears directly under the "identicality" paragraph, and is styled as follows:

````
    {% if stage and stage < 60 %}
    <p class=draft_type><span lang=EN-US><span style='mso-spacerun:yes'> </span></span><span
    lang=ZH-CN>（{{ stageabbr }}）</span></p>
  <p class=draft_type>
    {% if stage == 30 %}
  <a name=YZBS></a><span
  style='mso-bookmark:YZBS'><span lang=ZH-CN style='mso-no-proof:yes'>在提交反馈意见时，请将您知道的相关专利连同支持文件一并附上。</span><span
  lang=EN-US></span></span><span
  style='mso-bookmark:YZBS'></span>
    {% endif %}
  </p>
    <p class=draft_editorial><span lang=EN-US>
       {% if revdate %}
    <span lang=ZH-CN>（本稿完成日期：</span><span lang=EN-US>{{ revdate }}）</span>
       {% endif %}
   </span></p>
        {% endif %}
````

````
p.draft_type, li.draft_type, div.draft_type
	{mso-style-name:封面标准文稿类别; //  NAME: Cover page standard draft type 
	mso-style-unhide:no;
	mso-style-parent:"";
	margin-top:0.78cm;
	margin-right:0cm;
	margin-bottom:0cm;
	margin-left:0cm;
	margin-bottom:.0001pt;
	text-align:center;
	line-height:20.0pt;
	mso-line-height-rule:exactly;
	mso-pagination:widow-orphan;
	font-size:12.0pt;
	mso-bidi-font-size:10.0pt;
	font-family:SimSun;
	mso-hansi-font-family:"Times New Roman";
	mso-bidi-font-family:"Times New Roman";
	mso-ansi-language:EN-US;
	mso-fareast-language:ZH-CN;}
p.draft_editorial, li.draft_editorial, div.draft_editorial
	{mso-style-name:封面标准文稿编辑信息; //  NAME: Cover page standard draft editorial information 
	mso-style-unhide:no;
	mso-style-parent:"";
	margin-top:0.32cm;
	margin-right:0cm;
	margin-bottom:0cm;
	margin-left:0cm;
	margin-bottom:.0001pt;
	text-align:center;
	line-height:9.0pt;
	mso-line-height-rule:exactly;
	mso-pagination:widow-orphan;
	font-size:10.5pt;
	mso-bidi-font-size:10.0pt;
	font-family:SimSun;
	mso-hansi-font-family:"Times New Roman";
	mso-bidi-font-family:"Times New Roman";
	mso-ansi-language:EN-US;
	mso-fareast-language:ZH-CN;}
````

3. Just the cover page. I will have to overhaul the styling of the remaining HTML to align with GB/T 1.1, but I'll take on that task.

**Comment by ronaldtse** [comment]
Reading the word style sheet above gave me a headache. :wink:

Wouldn’t it be better if we just generate the HTML separately from Word HTML, make it as semantically sane as possible, so @pierrefortier won’t need to handle the `mso-*` and multiple `<span>` stuff?

**Comment by opoudjis** [comment]
The stylesheet is not meant for human readers. And the HTML generation already strips out all mso-* styles from the HTML instance. There is no point in splitting the stylesheet in two manually, when the automated stripping works.

Pierre is doing the stylesheet from scratch anyway; it'll be my job to merge the Word and HTML css when all is done.

**Comment by ronaldtse** [comment]
If we keep a single stylesheet for Word HTML and HTML, it could be difficult to maintain later on. Isn't it easier if we just let @pierrefortier do the HTML stylesheet from scratch and then directly use it? It'll save us the work on merging/synching CSS too. Word is word, HTML is HTML, right?

**Comment by opoudjis** [comment]
> Word is word, HTML is HTML, right?

No. Two completely independent stylesheets implementing the same formatting requirements is not a good idea—particularly for maintainability. And I do not agree that a single stylesheet, with Word styles signalled explicitly, is harder to maintain than two autonomous instances. (If anything, it's *easier* to maintain than two stylesheets with includes.)

**Comment by ronaldtse** [comment]
Hold on... there are two separate topics:
* should HTML and Word HTML be separate? 
* should the CSS applied to HTML and Word HTML be separate?

The consequence of having them so tightly coupled means that an HTML person (i.e. Pierre) won't be able to take the burden of the HTML styling independently, because it would affect the Word HTML output.

To me I vote "yes" to both questions because HTML and Word HTML can be managed by different people independently. @opoudjis are you "no" for both, or is there one "yes"? :wink:

**Comment by opoudjis** [comment]
I'm actually no to both, because of the substantial commonality between Word HTML and HTML HTML; and Pierre may be looking at just the HTML, but I end up having to look at everything. If one person's maintaining across the lot, then you want to minimise the autonomy of them.

But you're the boss, Ronald. :)

**Comment by ronaldtse** [comment]
@pierrefortier perhaps we can continue on the two optimized formats here?

@opoudjis I know we’ve been avoiding this question but for the long term we should really split the pure HTML vs Word HTML output. This way at least people like me can edit the HTML layout without breaking Word.

**Comment by opoudjis** [comment]
@ronaldtse Does that mean the Word HTML output class no longer inheriting from the pure HTML class, but replicating the common code?

**Comment by ronaldtse** [comment]
@opoudjis yes as we have discussed the HTML / Word-HTML split is under way. Thanks!

**Comment by opoudjis** [comment]
In fact, the split is done: https://github.com/riboseinc/asciidoctor-gb/tree/master/lib/isodoc/gb shows you gbhtmlconvert.rb gbwordconvert.rb, which are different, and gbhtmlrendert.rb gbwordrender.rb, which are identical, and there is no longer any inheritance of one from the other.

... @ronaldtse, does this ticket need to stay open?

**Comment by ronaldtse** [comment]
@opoudjis then could we put two HTML files in this repo, one for the Word styling and another for pure HTML styling?

@pierrefortier could we make the HTML version look more like the original page? And in fact, the isodoc styling (https://github.com/riboseinc/isodoc-style) you made was classy and professional looking -- this one could will definitely benefit from your attention 😉 

* Here we also need both human-optimized vs compliance-optimized HTML styling.
* The Word doc is only compliance-optimized (i.e. identical to the sample)

**Comment by opoudjis** [comment]
Right, so: I dump two HTML files here, one native HTML, and one Word HTML, for Pierre to work with. Pierre, the Word HTML file is gonna be ugly, but that's what I have to deal with in Word and DOC: it's HTML 4, with very primitive CSS (selectors only work with immediate children).

**Comment by ronaldtse** [comment]
Exactly, and the pure HTML version should be pure HTML5 👍

**Comment by opoudjis** [comment]
HTML doc: 
[rice.html.zip](https://github.com/riboseinc/gbdoc-style/files/2173562/rice.html.zip)
Word HTML:
[rice.doc.html.zip](https://github.com/riboseinc/gbdoc-style/files/2173563/rice.doc.html.zip)
Corresponding Doc:
[rice.doc.zip](https://github.com/riboseinc/gbdoc-style/files/2173564/rice.doc.zip)

Saving the Word document with styles updated should be fine, but I'm still going to have to save the doc as HTML to extract the stylesheet...

**Comment by opoudjis** [comment]
And the HTML is meant to have been pure HTML 5 for a while now, because it is inherited from asciidoctor-iso.

**Comment by pierrefortier** [comment]
Here is an update to the HTML doc style. 
[rice.html-v2.zip](https://github.com/riboseinc/gbdoc-style/files/2174132/rice.html-v2.zip)

**Comment by ronaldtse** [comment]
@pierrefortier the content/body looks good but the cover page probably needs more styling. And this will be the human-optimized styling, we need another style for compliance-optimized. Thanks!

Cover page now:
- "NY" is the document standard prefix, it looks enormous now
- (@opoudjis there should only be a single NY/T rather than "NY/T NY/T XXXXX")

![screen shot 2018-07-09 at 12 03 29 pm](https://user-images.githubusercontent.com/11865/42430180-3b5255c6-8370-11e8-9621-8a1820105182.png)

**Comment by opoudjis** [comment]
The enormous NY is in fact the Standards Agency Logo; recall that we only have a handful of those, and for the rest we use the enlarged standards initials. So it is intentional to mirror the Word coverpage.

I'm aware of the duplicated NY/T, and I was going to defer investigating it. We'll keep that in this ticket.

**Comment by ronaldtse** [comment]
Right, but perhaps @pierrefortier could help style those initials prettily 😉

**Comment by ronaldtse** [comment]
@pierrefortier any update here? @opoudjis would like to integrate this soon, especially for https://github.com/riboseinc/gmt-0015-2012 (has Chinese and English copies now). Thanks!

**Comment by pierrefortier** [comment]
Here is an update to the style (including compliance-optimized)

[rice.html-v3.zip](https://github.com/riboseinc/gbdoc-style/files/2216315/rice.html-v3.zip)

**Comment by ronaldtse** [comment]
@pierrefortier thanks for this, but both versions do not look anything like this:


![](https://user-images.githubusercontent.com/11865/38401527-d0a893ce-3988-11e8-9ba3-9a9fa3b2a646.png)

Can you help code this layout for the "compliance" style? Thanks!

**Comment by pierrefortier** [comment]
My appologies, I must have gotten confused through the different versions. Here it is:

[gbdoc-style.zip](https://github.com/riboseinc/gbdoc-style/files/2218953/gbdoc-style.zip)

**Comment by ronaldtse** [comment]
@pierrefortier this works! @opoudjis any further changes needed, or we can integrate this now?

**Comment by opoudjis** [comment]
I'm sure I'll find plenty to modify in the CSS to align it with the latest version; but I'll do that in 
https://github.com/riboseinc/asciidoctor-gb/issues/93

**Comment by opoudjis** [comment]
Note that you have two stylesheets, @pierrefortier, which i'm merging into one. I am having style-iso override style-A4, as is the case in your sample, but there may be some queries when this is done.

**Comment by opoudjis** [comment]
I've merged the stylesheets, and run it through an English-language sector standard. The dimensions don't seem to quite be there, although admittedly you had not factored in a bilingual title.

Could I ask you to tweak the built in CSS stylesheet in the attached, so that it matches the prescribed dimensions? My particular concern is about the vertical placement of title components (which will be exacerbated with the optional "draft" warnings.)

[rice_compliant.html.zip](https://github.com/riboseinc/gbdoc-style/files/2237924/rice_compliant.html.zip)

**Comment by pierrefortier** [comment]
Sure thing, @opoudjis , let me know if this works:

[rice_compliant.html 2.zip](https://github.com/riboseinc/gbdoc-style/files/2238098/rice_compliant.html.2.zip)

**Comment by opoudjis** [comment]
... I also need to enable the display of coverpage-stage-block. Let me try to adjust the measurements myself before coming back to you...

**Comment by opoudjis** [comment]
I'm ok now, though I have ended up making coverpage-banner 177.5mm high, to comply with A4 spec.
